\\ Решение третьей задачи
js-tasks-ru/jsbasic-20210520_vaya pull request #3
Opened 2021-06-03 13:54 UTC by ValeriyaRipyanchina

2021-06-03 13:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-03 15:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-03 16:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-03 17:05 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-06 22:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-06 22:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-06 22:24 UTC, ValeriyaRipyanchina reviewed
\\коррекция третьей задачи

2021-06-07 03:05 UTC, koalex requested changes

2021-06-07 03:05 UTC, koalex commented on 1-module/3-task/index.js
> +  return str[0].toUpperCase() + str.slice[1];
`str.slice[1]` надо заменить на `str.slice(1)`

2021-06-07 03:05 UTC, koalex commented on 1-module/4-task/index.js
> +  return lowerStr.includes('1xBet') || lowerStr.includes('XXX');
Если ты привела строку к нижнему регистру, то и сравнивать нужно тоже с нижним регистром.
`lowerStr.includes('1xBet') || lowerStr.includes('XXX')`
заменить на
`lowerStr.includes('1xbet') || lowerStr.includes('xxx')`

2021-06-07 03:05 UTC, koalex commented on 1-module/5-task/index.js
> +  str.slice(0, maxlength - 1) + '...' : str;
Тут можешь поменять три точки на это `…`. Это выглядит как три точки, только это троеточие. Просто замени и всё :)

2021-06-07 12:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-07 12:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-07 12:44 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-06-07 12:52 UTC, koalex approved these changes

2021-06-07 12:53 UTC, merged