Решение задач 2 модуля
js-tasks-ru/jsbasic-20210520_vaya pull request #4
Opened 2021-06-07 17:53 UTC by ValeriyaRipyanchina

2021-06-07 17:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-10 20:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-10 20:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 09:30 UTC, koalex requested changes

2021-06-11 09:30 UTC, koalex commented on 2-module/3-task/index.js
> +alert( calculator.sum() );
удали `alert`-ы

2021-06-11 09:30 UTC, koalex commented on 2-module/3-task/index.js
> +  read() {
Неправильно. Должно быть так:
```
read(a, b) {
  this.a = +a;
  this.b = +b;
}
```

2021-06-11 09:30 UTC, koalex commented on 2-module/3-task/index.js
> +alert( calculator.sum() );
и `calculator.read();`

2021-06-11 12:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 12:53 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-06-11 13:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 13:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 13:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 13:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 15:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 15:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 16:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 16:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 16:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-11 19:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-15 12:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2021-06-15 12:05 UTC, koalex approved these changes

2021-06-15 12:06 UTC, merged